### ISSUE TITLE
PostgreSQL commands not working

### ISSUE THREAD

**Issue by Defuse4045** [kndndrj/nvim-dbee#87] opened 2024-02-09 23:03 UTC
psql commands such as the one used to describe a table fail to execute with a syntax error. 
![image](https://github.com/kndndrj/nvim-dbee/assets/159588995/8421ee8f-dc69-42e8-9225-2c19cd29075c)
In comparison, they work with  other plugins such as vim-dadbod & vim-dadbod-ui
![image](https://github.com/kndndrj/nvim-dbee/assets/159588995/86723b78-797b-4081-8149-f6b4ef02bb56)

**Comment by MattiasMTS** [comment] 2024-02-12 15:51
This fails presumably because the backend is using https://pkg.go.dev/database/sql under the hood, compared to vim-dadbod, which uses `psql` cli under the hood.

If you want to describe a table you could make use of the "helpers" by hitting "enter" on the table you want to describe. For postgres, you have the following helpers: https://github.com/kndndrj/nvim-dbee/blob/master/dbee/adapters/postgres.go#L69-L87

**Comment by willruggiano** [comment] 2024-02-13 18:57
Not that it addresses your situation exactly, but I recently discovered [pgddl](https://github.com/lacanoid/pgddl) which I added as an extra helper in my [personal configuration](https://github.com/willruggiano/neovim.drv/commit/8de7a3de1c8dd52393f2977ca810aa7b578932c8) which lets me generate DDL scripts for database objects. I use it just for CREATE scripts, but the extension can generate DROP scripts as well as scripts that include the entire dependency tree.

**Comment by kndndrj** [comment] 2024-04-09 03:27
As @MattiasMTS said - we are using a different backend - therefore this is not a bug. Closing.

**Closed by kndndrj** 2024-04-09 03:27 UTC
